//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int tipo_asistencia { get; set; }
        public int id_asistencias_has_alumnos { get; set; }
    
        public virtual asistencias_has_alumnos asistencias_has_alumnos { get; set; }
    }
}
