//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class docentes_materias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public docentes_materias()
        {
            this.asistencias_has_alumnos = new HashSet<asistencias_has_alumnos>();
        }
    
        public int id { get; set; }
        public int iddocente { get; set; }
        public int idmateria { get; set; }
        public int idperiodo { get; set; }
        public byte lunes { get; set; }
        public System.TimeSpan hora_lunes { get; set; }
        public byte martes { get; set; }
        public byte miercoles { get; set; }
        public byte jueves { get; set; }
        public byte viernes { get; set; }
        public byte sabado { get; set; }
        public System.TimeSpan hora_martes { get; set; }
        public System.TimeSpan hora_miercoles { get; set; }
        public System.TimeSpan hora_jueves { get; set; }
        public System.TimeSpan hora_viernes { get; set; }
        public System.TimeSpan hora_sabado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asistencias_has_alumnos> asistencias_has_alumnos { get; set; }
        public virtual docente docente { get; set; }
        public virtual periodo periodo { get; set; }
        public virtual materia materia { get; set; }
    }
}
