//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EurekaBD : DbContext
    {
        public EurekaBD()
            : base("name=EurekaBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumno> alumnos { get; set; }
        public virtual DbSet<asistencia> asistencias { get; set; }
        public virtual DbSet<asistencias_has_alumnos> asistencias_has_alumnos { get; set; }
        public virtual DbSet<docente> docentes { get; set; }
        public virtual DbSet<docentes_materias> docentes_materias { get; set; }
        public virtual DbSet<materia> materias { get; set; }
        public virtual DbSet<periodo> periodos { get; set; }
    }
}
